# Generated by Django 4.1.7 on 2023-03-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('Image', models.FileField(upload_to='files/images')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('jobtitle', models.CharField(max_length=300, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('Image', models.FileField(upload_to='files/images')),
                ('ImageName', models.CharField(max_length=300, null=True)),
                ('slideImage', models.FileField(upload_to='files/images')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('amount', models.CharField(max_length=100)),
                ('Doctor', models.ManyToManyField(to='webs.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('servicesproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webs.servicesproperty')),
                ('Price', models.FileField(upload_to='files/images')),
            ],
            bases=('webs.servicesproperty',),
        ),
        migrations.CreateModel(
            name='WEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('Title', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='files/images')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('Image', models.FileField(upload_to='files/images')),
                ('silderImage', models.FileField(upload_to='files/images')),
                ('FaviconIco', models.FileField(upload_to='files/images')),
                ('Description', models.CharField(max_length=300, null=True)),
                ('keywords', models.CharField(max_length=300, null=True)),
                ('authorLinke', models.CharField(max_length=300, null=True)),
                ('Doctor', models.ManyToManyField(to='webs.doctors')),
                ('Landingpage', models.ManyToManyField(to='webs.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('knew', models.CharField(choices=[('عرفتنا منين', 'عرفتنا منين'), ('تأمين', 'تأمين'), ('صديق ', 'صديق '), ('أسرة', 'أسرة'), ('الجيران', 'الجيران'), ('جوجل ', 'جوجل '), ('واتساب', 'واتساب'), ('سناب', 'سناب'), ('انستقرام', 'انستقرام'), ('تويتر', 'تويتر'), ('فيس بوك ', 'فيس بوك '), ('تيك توك', 'تيك توك'), ('يوتيوب ', 'يوتيوب '), ('البريد الإلكتروني', 'البريد الإلكتروني'), ('موقع', 'موقع'), ('آخر', 'آخر')], default='عرفتنا منين', max_length=30)),
                ('Message', models.CharField(max_length=500)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webs.doctors')),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webs.web')),
                ('LandingPage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webs.landingpage')),
            ],
        ),
    ]
