# Generated by Django 4.1.7 on 2023-03-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='info',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('SectioN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='webs.web')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True)),
                ('answer', models.CharField(max_length=300)),
                ('WEBQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qestions', to='webs.web')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('InsuranceImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='webs.web')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='files/images')),
                ('imagename', models.CharField(max_length=300, null=True)),
                ('WEBImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='webs.web')),
            ],
        ),
    ]
