# Generated by Django 4.1.7 on 2023-03-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_web_info_section_questions_insurance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.FileField(default='', upload_to='files/images'),
            preserve_default=False,
        ),
    ]
