# Generated by Django 4.1.7 on 2023-03-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0003_section_description_section_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='files/images')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='files/images')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='servicesproperty',
            old_name='amount',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='servicesproperty',
            name='price',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesproperty',
            name='slideImage1',
            field=models.FileField(default='', upload_to='files/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesproperty',
            name='slideImage2',
            field=models.FileField(default='', upload_to='files/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicesproperty',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
