# Generated by Django 4.1.7 on 2023-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0004_landingpagedescription_landingpageimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeforeImage', models.FileField(upload_to='files/images')),
                ('AfterImage', models.FileField(upload_to='files/images')),
                ('name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='Price',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='DescriptionPage',
            field=models.ManyToManyField(to='webs.landingpagedescription'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='PricePage',
            field=models.ManyToManyField(to='webs.landingpageprice'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='QuestionsPage',
            field=models.ManyToManyField(to='webs.landingpagequestions'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ReviewsPage',
            field=models.ManyToManyField(to='webs.landingpagereviews'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='imagePage',
            field=models.ManyToManyField(to='webs.landingpageimage'),
        ),
    ]
