# Generated by Django 4.1.7 on 2023-03-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0006_landingpage_beforeafterpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageimage',
            name='Name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
