# Generated by Django 4.1.7 on 2023-03-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0007_landingpageimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpagebeforeafter',
            old_name='AfterImage',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='landingpagebeforeafter',
            name='BeforeImage',
        ),
        migrations.RemoveField(
            model_name='landingpagebeforeafter',
            name='name',
        ),
        migrations.AddField(
            model_name='landingpagebeforeafter',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landingpagebeforeafter',
            name='Title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
