# Generated by Django 4.1.7 on 2023-03-20 14:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0008_rename_afterimage_landingpagebeforeafter_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
