# Generated by Django 4.1.7 on 2023-03-20 14:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0009_booking_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CA'),
        ),
    ]
