# Generated by Django 4.1.7 on 2023-03-20 18:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0010_alter_booking_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='STATUS',
            field=models.CharField(choices=[('انتظار', 'انتظار'), ('ارسل', 'ارسل')], default='انتظار', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='knew',
            field=models.CharField(choices=[('كيف عرفتنا', 'كيف عرفتنا'), ('تأمين', 'تأمين'), ('صديق ', 'صديق '), ('أسرة', 'أسرة'), ('الجيران', 'الجيران'), ('جوجل ', 'جوجل '), ('واتساب', 'واتساب'), ('سناب', 'سناب'), ('انستقرام', 'انستقرام'), ('تويتر', 'تويتر'), ('فيس بوك ', 'فيس بوك '), ('تيك توك', 'تيك توك'), ('يوتيوب ', 'يوتيوب '), ('البريد الإلكتروني', 'البريد الإلكتروني'), ('موقع', ' موقع الإلكتروني'), ('آخر', 'آخر')], default='كيف عرفتنا', max_length=30),
        ),
    ]
