# Generated by Django 4.1.7 on 2023-03-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0011_booking_status_alter_booking_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='PhoneNumber',
        ),
    ]
