# Generated by Django 4.1.7 on 2023-03-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0012_remove_booking_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='web',
            field=models.CharField(max_length=30),
        ),
    ]
