# Generated by Django 4.1.7 on 2023-03-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0014_alter_booking_status_alter_booking_knew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='Address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='OpeningHours',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='PHONE',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='Twitterlinke',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='Whatsapp',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='facebooklinke',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='instagramlinke',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='linkedinlinke',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='snapchat',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
