# Generated by Django 4.1.7 on 2023-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0015_web_address_web_openinghours_web_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesproperty',
            name='homepagelink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
