# Generated by Django 4.1.7 on 2023-03-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0016_servicesproperty_homepagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='OpeningHours',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='PHONE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='Twitterlinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='Whatsapp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='facebooklinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='instagramlinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='linkedinlinke',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='web',
            name='snapchat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
