# Generated by Django 4.1.7 on 2023-03-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0019_alter_servicesproperty_webname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webs.doctors'),
        ),
    ]
